ToontownStart: Polling for game2 to finish...
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  tti-retro-dev
Preloading avatars...
Done preloading avatars.
{401000001: <toontown.distributed.ToontownDistrict.ToontownDistrict instance at 0x2E3F7530>}
entering active SC menu
local
1
Reading DNA file... phase_4/dna/storage.dna
Reading DNA file... phase_3.5/dna/storage_interior.dna
frame rate: 46.5 fps|0.007d|12 avs||339|345||0x10de|0x11c8|487.1MB|524.4MB|8136.0MB|955|nt.2.6.2|3.601,3.601|4,8 cpus|OpenGL
Warning: NodePath.remove() is deprecated.  Use remove_node() instead.
Warning: NodePath.remove() is deprecated.  Use remove_node() instead.
Traceback (most recent call last):
  File "D:\Usuario\Downloads\tts\TTISource\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 613, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "D:\Usuario\Downloads\tts\TTISource\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 620, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "otp\distributed\OTPClientRepository.py", line 1873, in handleDatagram
    self.handler(msgType, di)
  File "otp\distributed\OTPClientRepository.py", line 1484, in handlePlayGame
    self.handleUpdateField(di)
  File "otp\distributed\OTPClientRepository.py", line 2191, in handleUpdateField
    self.__doUpdate(doId, di, ovUpdated)
  File "otp\distributed\OTPClientRepository.py", line 2199, in __doUpdate
    do.dclass.receiveUpdate(do, di)
  File "toontown\suit\DistributedLawbotBoss.py", line 236, in loadCogs
    head = Suit.attachSuitHead(self.stunnedCogsPanel, cog)
  File "toontown\suit\Suit.py", line 300, in attachSuitHead
    head = node.attachNewNode('head')
AssertionError: _error_type == ET_ok at line 725 of panda/src/pgraph/nodePath.cxx
Traceback (most recent call last):
  File "otp\otpbase\OTPBase.py", line 239, in run
    taskMgr.run()
  File "D:\Usuario\Downloads\tts\TTISource\Panda3D-1.9.0\direct\task\Task.py", line 502, in run
    self.step()
  File "D:\Usuario\Downloads\tts\TTISource\Panda3D-1.9.0\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "D:\Usuario\Downloads\tts\TTISource\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 613, in readerPollUntilEmpty
    while self.readerPollOnce():
  File "D:\Usuario\Downloads\tts\TTISource\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 620, in readerPollOnce
    self.handleDatagram(self.private__di)
  File "otp\distributed\OTPClientRepository.py", line 1873, in handleDatagram
    self.handler(msgType, di)
  File "otp\distributed\OTPClientRepository.py", line 1484, in handlePlayGame
    self.handleUpdateField(di)
  File "otp\distributed\OTPClientRepository.py", line 2191, in handleUpdateField
    self.__doUpdate(doId, di, ovUpdated)
  File "otp\distributed\OTPClientRepository.py", line 2199, in __doUpdate
    do.dclass.receiveUpdate(do, di)
  File "toontown\suit\DistributedLawbotBoss.py", line 236, in loadCogs
    head = Suit.attachSuitHead(self.stunnedCogsPanel, cog)
  File "toontown\suit\Suit.py", line 300, in attachSuitHead
    head = node.attachNewNode('head')
AssertionError: _error_type == ET_ok at line 725 of panda/src/pgraph/nodePath.cxx
